{{- if .Values.global.deploymentHooks.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "panoptica-kubernetes-integration.fullname" . }}-pre-sync
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "panoptica-kubernetes-integration.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  {{- with .Values.global.deploymentHooks.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: panoptica.app/release
data:
  chartValues: {{ toYaml $.Values | b64enc }}
  chartVersion: {{ .Chart.Version | b64enc }}
  deploymentStatus: {{ printf "%s" "pending-install" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "panoptica-kubernetes-integration.fullname" . }}-post-sync
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "panoptica-kubernetes-integration.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation    
  {{- with .Values.global.deploymentHooks.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: panoptica.app/release
data:
  chartValues: {{ toYaml $.Values | b64enc }}
  chartVersion: {{ .Chart.Version | b64enc }}
  deploymentStatus: {{ printf "%s" "deployed" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "panoptica-kubernetes-integration.fullname" . }}-sync-fail
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "panoptica-kubernetes-integration.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: SyncFail
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  {{- with .Values.global.deploymentHooks.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}    
type: panoptica.app/release
data:
  chartValues: {{ toYaml $.Values | b64enc }}
  chartVersion: {{ .Chart.Version | b64enc }}
  deploymentStatus: {{ printf "%s" "failed" | b64enc }}
---
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "panoptica-kubernetes-integration.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "panoptica-kubernetes-integration.labels" . | nindent 4 }}
type: panoptica.app/release
data:
  chartValues: {{ toYaml $.Values | b64enc }}
  chartVersion: {{ .Chart.Version | b64enc }}
  deploymentStatus: {{ printf "%s" "untrackable" | b64enc }}
---
{{- end }}
