global:
  panopticaIntegration:
    id: 6837ce65-7b62-4055-9370-def889d89f5a
    kspm:
      enabled: true
    apiSecurity:
      enabled: false
    cdr:
      enabled: false
  mgmtHostname: "production.demo.panoptica.app"

panoptica-kubernetes-integration:
  kubernetes-integration-deployment-controller:
    api:
      url: "deploymentmanager.staging.panoptica.app"

    secret:
      token: eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2F1dGgua2lzLnBhbm9wdGljYS5pbyIsInN1YiI6ImFkYzo2ODM3Y2U2NS03YjYyLTQwNTUtOTM3MC1kZWY4ODlkODlmNWEiLCJhdWQiOlsiL2ludGVncmF0aW9ucy82ODM3Y2U2NS03YjYyLTQwNTUtOTM3MC1kZWY4ODlkODlmNWEiLCIvcmVsZWFzZXMiXSwic2NwIjpbImlhbS5nbG9iYWwucGFub3B0aWNhLms4c2NsdXN0ZXJzZXJ2aWNlLmludGVncmF0aW9ucy5kZXBsb3ltZW50Om1hbmFnZSIsImlhbS5nbG9iYWwucGFub3B0aWNhLms4c2NsdXN0ZXJzZXJ2aWNlLmludGVncmF0aW9uczpyZWFkIiwiaWFtLmdsb2JhbC5wYW5vcHRpY2EuazhzY2x1c3RlcnNlcnZpY2UuaW50ZWdyYXRpb25zOm1hbmFnZSIsImlhbS5nbG9iYWwucGFub3B0aWNhLms4c2NsdXN0ZXJzZXJ2aWNlLnJlbGVhc2VzOnJlYWQiXSwidGVuYW50IjoiYjQ5MjdkZWEtODdmZS00YTNiLTk1ZTktNGU1MjJlNTk0NGFjIn0.pBz6X4zavkkRsMR7RWB8kKCSvPHv--JH6lfNebtfKBe6xiWggy7eDkw_KAM-qMM-l_A4u_JWCwaaGfK7IpHxNw

    syncIntegrationJob:
      api:
        url: "k8s-integration.staging.panoptica.app"
  k8sec-controller:
    controller:
      secret:
        sharedSecret: vfL6xRfNwtGMQ3q/DjgE0ouUwdGAAiBkDpjqoR05q74=
      agentID: b8b72206-2966-4430-9205-a242e75230ff