global:
  panopticaIntegration:
    id: c28a4cc6-9945-446b-9fb7-7352bd1fc82f
    kspm:
      enabled: true
    apiSecurity:
      enabled: false
    cdr:
      enabled: false
  mgmtHostname: "production.demo.panoptica.app"

panoptica-kubernetes-integration:
  kubernetes-integration-deployment-controller:
    api:
      url: "deploymentmanager.staging.panoptica.app"

    secret:
      token: eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2F1dGgua2lzLnBhbm9wdGljYS5pbyIsInN1YiI6ImFkYzpjMjhhNGNjNi05OTQ1LTQ0NmItOWZiNy03MzUyYmQxZmM4MmYiLCJhdWQiOlsiL2ludGVncmF0aW9ucy9jMjhhNGNjNi05OTQ1LTQ0NmItOWZiNy03MzUyYmQxZmM4MmYiLCIvcmVsZWFzZXMiXSwic2NwIjpbImlhbS5nbG9iYWwucGFub3B0aWNhLms4c2NsdXN0ZXJzZXJ2aWNlLmludGVncmF0aW9ucy5kZXBsb3ltZW50Om1hbmFnZSIsImlhbS5nbG9iYWwucGFub3B0aWNhLms4c2NsdXN0ZXJzZXJ2aWNlLmludGVncmF0aW9uczpyZWFkIiwiaWFtLmdsb2JhbC5wYW5vcHRpY2EuazhzY2x1c3RlcnNlcnZpY2UuaW50ZWdyYXRpb25zOm1hbmFnZSIsImlhbS5nbG9iYWwucGFub3B0aWNhLms4c2NsdXN0ZXJzZXJ2aWNlLnJlbGVhc2VzOnJlYWQiXSwidGVuYW50IjoiYjQ5MjdkZWEtODdmZS00YTNiLTk1ZTktNGU1MjJlNTk0NGFjIn0.N20EN2fza266_QenIV-wegNfOcPUHIdaM-JJJDt41IuTezlNg3ReLzj5_Zbr3SCKXDNJTzhkPGqjY9VPtC6xEQ

    syncIntegrationJob:
      api:
        url: "k8s-integration.staging.panoptica.app"
  k8sec-controller:
    controller:
      secret:
        sharedSecret: Ko75JytWb8RUHjxl/Bl25GJOm+UBDcRaVxsNGbVWx5Q=
      agentID: 08c00fc2-b2f8-49a7-b7c6-372ebc23fd74